services:

  library:
    build: ./library
    environment:
      - PORT=3000
    ports:
      - 80:3000

  counter:
    build: ./counter
    environment:
      - PORT=3001
      - REDIS_URL=redis://storage
    ports:
      - 81:3001
    depends_on:
      - storage
  storage:
    image: redis
    volumes:
      - ./data:/data
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/"
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
    